package com.wasabisushi.persistence.entity;
// Generated Nov 3, 2022, 11:31:49 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name = "cliente", uniqueConstraints = @UniqueConstraint(columnNames = "cpf"))
public class Cliente implements java.io.Serializable {

	private Integer idCliente;
	private String cpf;
	private String nome;
	private String endereco;
	private String telefone;
	private String NCartao;
	private Set<Pedido> pedidos = new HashSet<Pedido>(0);

	public Cliente() {
	}
	
	// CONSTRUTOR CRIADO APENAS PARA MOCK
	public Cliente(String nome) {
		this.nome = nome;
	}
	
	public Cliente(Integer idCliente, String cpf, String nome, String endereco, String telefone, String NCartao) {
		this.idCliente = idCliente;
		this.cpf = cpf;
		this.nome = nome;
		this.endereco = endereco;
		this.telefone = telefone;
		this.NCartao = NCartao;
	}

	public Cliente(String cpf, String nome, String endereco, String telefone, String NCartao) {
		this.cpf = cpf;
		this.nome = nome;
		this.endereco = endereco;
		this.telefone = telefone;
		this.NCartao = NCartao;
	}

	public Cliente(String cpf, String nome, String endereco, String telefone, String NCartao, Set<Pedido> pedidos) {
		this.cpf = cpf;
		this.nome = nome;
		this.endereco = endereco;
		this.telefone = telefone;
		this.NCartao = NCartao;
		this.pedidos = pedidos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idCliente", unique = true, nullable = false)
	public Integer getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(Integer idCliente) {
		this.idCliente = idCliente;
	}

	@Column(name = "cpf", unique = true, nullable = false, length = 45)
	public String getCpf() {
		return this.cpf;
	}

	public void setCpf(String cpf) {
		this.cpf = cpf;
	}

	@Column(name = "nome", nullable = false, length = 45)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "endereco", nullable = false, length = 45)
	public String getEndereco() {
		return this.endereco;
	}

	public void setEndereco(String endereco) {
		this.endereco = endereco;
	}

	@Column(name = "telefone", nullable = false, length = 45)
	public String getTelefone() {
		return this.telefone;
	}

	public void setTelefone(String telefone) {
		this.telefone = telefone;
	}

	@Column(name = "n_cartao", nullable = false, length = 45)
	public String getNCartao() {
		return this.NCartao;
	}

	public void setNCartao(String NCartao) {
		this.NCartao = NCartao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
	public Set<Pedido> getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(Set<Pedido> pedidos) {
		this.pedidos = pedidos;
	}

}
