package com.wasabisushi.persistence.entity;
// Generated Nov 3, 2022, 11:31:49 PM by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Pedido generated by hbm2java
 */
@Entity
@Table(name = "pedido")
public class Pedido implements java.io.Serializable {

	private int idPedido;
	private Cliente cliente;
	private Produto produto;
	private String valorTotal;

	public Pedido() {
	}

	public Pedido(int idPedido, Cliente cliente, Produto produto) {
		this.idPedido = idPedido;
		this.cliente = cliente;
		this.produto = produto;
	}

	public Pedido(int idPedido, Cliente cliente, Produto produto, String valorTotal) {
		this.idPedido = idPedido;
		this.cliente = cliente;
		this.produto = produto;
		this.valorTotal = valorTotal;
	}
	
	public Pedido( Cliente cliente, Produto produto, String valorTotal) {
	
		this.cliente = cliente;
		this.produto = produto;
		this.valorTotal = valorTotal;
	}

	@Id

	@Column(name = "idPedido", unique = true, nullable = false)
	public int getIdPedido() {
		return this.idPedido;
	}

	public void setIdPedido(int idPedido) {
		this.idPedido = idPedido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idCliente", nullable = false)
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idProduto", nullable = false)
	public Produto getProduto() {
		return this.produto;
	}

	public void setProduto(Produto produto) {
		this.produto = produto;
	}

	@Column(name = "valorTotal", length = 45)
	public String getValorTotal() {
		return this.valorTotal;
	}

	public void setValorTotal(String valorTotal) {
		this.valorTotal = valorTotal;
	}

}
