package com.wasabisushi.persistence.entity;
// Generated Nov 3, 2022, 11:31:49 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Produto generated by hbm2java
 */
@Entity
@Table(name = "produto")
public class Produto implements java.io.Serializable {

	private int idProduto;
	private String nome;
	private String categoria;
	private String descricao;
	private String preco;
	private Set<Pedido> pedidos = new HashSet<Pedido>(0);

	public Produto() {
	}

	public Produto(int idProduto) {
		this.idProduto = idProduto;
	}
	
	// CONSTRUTOR CRIADO A FINS DE TESTES NA VIEW
	public Produto(String nome) {
		this.nome = nome;
	}

	public Produto(int idProduto, String nome, String categoria, String descricao, String preco, Set<Pedido> pedidos) {
		this.idProduto = idProduto;
		this.nome = nome;
		this.categoria = categoria;
		this.descricao = descricao;
		this.preco = preco;
		this.pedidos = pedidos;
	}
	
	public Produto(String nome, String categoria, String descricao, String preco) {
		this.nome = nome;
		this.categoria = categoria;
		this.descricao = descricao;
		this.preco = preco;
	}
	
	// adicionado este contrutor para editar
	public Produto(int idProduto, String nome, String categoria, String descricao, String preco) {
		this.idProduto = idProduto;
		this.nome = nome;
		this.categoria = categoria;
		this.descricao = descricao;
		this.preco = preco;
	}

	@Id

	@Column(name = "idProduto", unique = true, nullable = false)
	public int getIdProduto() {
		return this.idProduto;
	}

	public void setIdProduto(int idProduto) {
		this.idProduto = idProduto;
	}

	@Column(name = "nome", length = 45)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "categoria", length = 45)
	public String getCategoria() {
		return this.categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}

	@Column(name = "descricao", length = 200)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "preco", length = 45)
	public String getPreco() {
		return this.preco;
	}

	public void setPreco(String preco) {
		this.preco = preco;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produto")
	public Set<Pedido> getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(Set<Pedido> pedidos) {
		this.pedidos = pedidos;
	}

}
